### ISSUE TITLE
Broken documentation link

### ISSUE THREAD

**Issue by MarcoWorms** [tjhorner/node-launchpad-mk2#2]
Hi there! I was checking this out but the documentation link provided in readme.md is not working (https://tjhorner.com/node-launchpad-mk2/)

From what I've seen this project is 3 to 4 years old. If the documentation for this is still available would you mind re-uploading it?

Thanks!

**Comment by MarcoWorms** [comment]
I just found out that the docs are also on the repo hehe, sorry!

**Comment by tjhorner** [comment]
it's available at https://tjhorner.dev/node-launchpad-mk2/

I recently switched my GitHub Pages domain from tjhorner.com to tjhorner.dev

**Comment by tjhorner** [comment]
ok, I fixed the redirect

**Comment by MarcoWorms** [comment]
awesome! thanks!
